import os
from gradio_client import Client
from .tts_interface import TTSInterface

class GradioVITSTTS(TTSInterface):
    def __init__(self, api_url="http://127.0.0.1:7860/", speaker="Hana", language="日本語", speed=1.0):
        self.client = Client(api_url)
        self.speaker = speaker
        self.language = language
        self.speed = speed

    def generate_audio(self, text: str, output_path: str) -> str:
        """
        Calls your Gradio API to generate audio.
        """
        try:
            # client.predict returns [message, filepath] based on your documentation
            result = self.client.predict(
                text=text,
                speaker=self.speaker,
                language=self.language,
                speed=self.speed,
                api_name="/tts"
            )
            
            # result[1] is the temporary filepath generated by Gradio
            temp_audio_path = result[1]
            
            # Move/rename the file to the project's expected output_path
            if os.path.exists(temp_audio_path):
                import shutil
                shutil.move(temp_audio_path, output_path)
                return output_path
        except Exception as e:
            print(f"Error in Gradio VITS TTS: {e}")
            return None
